//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kv
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryList
    {
        public int Id { get; set; }
        public int Id_Extradition { get; set; }
        public Nullable<long> Current_balance { get; set; }
    
        public virtual Extradition Extradition { get; set; }
    }
}
